import re

# 原始字符串数据
source_data = """
[\\iota],
    [iota],
    [\\jmath],
    [dotless.j],
    [\\kappa],
    [kappa],
    [\\lambda],
    [lambda],
    [\\langle],
    [angle.l],
    [\\lbrace],
    [brace, brace.l],
    [\\lbrack],
    [bracket, bracket.l],
    [\\ldots],
    [dots, dots.l],
    [\\le ],
    [lt.eq],
    [\\leadsto],
    [arrow.squiggly],
    [\\leftarrow],
    [arrow.l],
    [\\leftthreetimes],
    [times.three.l],
    [\\leftrightarrow],
    [arrow.l.r],
    [\\lhd],
    [triangle.l],
    [\\ll],
    [lt.double],
    [\\longmapsto],
    [arrow.long.bar],
    [\\longrightarrow],
    [arrow.r.long],
    [\\ltimes],
    [times.l],
    [\\mapsto],
    [arrow.bar],
    [\\measuredangle],
    [angle.arc],
    [\\mid],
    [divides],
    [\\models],
    [models],
    [\\mp],
    [minus.plus],
    [\\mu],
    [mu],
    [\\nRightarrow],
    [arrow.double.r.not],
    [\\nabla],
    [nabla],
    [\\ncong],
    [tilde.equiv.not],
    [\\ne],
    [eq.not ],
    [\\neg],
    [not],
    [\\nmid],
    [divides.not],
    [\\notin],
    [in.not],
    [\\nleftarrow],
    [arrow.l.not],
    [\\nrightarrow],
    [arrow.r.not],
    [\\nsim],
    [tilde.not],
    [\\nu],
    [nu],
    [\\odot],
    [dot.circle],
    [\\oint],
    [integral.cont],
    [\\omega],
    [omega],
    [\\ominus],
    [minus.circle],
    [\\oplus],
    [plus.circle],
    [\\otimes],
    [times.circle],
    [\\parallel],
    [parallel],
    [\\partial],
    [diff],
    [\\perp],
    [perp],
    [\\phi],
    [phi.alt],
    [\\pi],
    [pi],
    [\\pm],
    [plus.minus],
    [\\prec],
    [prec],
    [\\preceq],
    [prec.eq],
    [\\prime],
    [prime],
    [\\prod],
    [product],
    [\\propto],
    [prop],
    [\\psi],
    [psi],
    [\\rangle],
    [angle.r],
    [\\rbrace],
    [brace.r],
    [\\rbrack],
    [bracket.r],
    [\\rhd],
    [triangle.r],
    [\\rho],
    [rho],
    [\\rightarrow],
    [arrow.r ],
    [\\rightthreetimes],
    [times.three.r],
    [\\rtimes],
    [times.r],
    [\\setminus],
    [without],
    [\\sigma],
    [sigma],
    [\\sim],
    [tilde],
    [\\simeq],
    [tilde.eq],
    [\\sqcap],
    [sect.sq],
    [\\sqcup],
    [union.sq],
    [\\star],
    [star],
    [\\subset],
    [subset],
    [\\subseteq],
    [subset.eq],
    [\\subsetneq],
    [subset.neq],
    [\\succ],
    [succ],
    [\\succeq],
    [succ.eq],
    [\\sum],
    [sum],
    [\\supset],
    [supset],
    [\\supseteq],
    [supset.eq],
    [\\supsetneq],
    [supset.neq],
    [\\tau],
    [tau],
    [\\theta],
    [theta],
    [\\times],
    [times],
    [\\to],
    [arrow.r],
    [\\triangle],
    [triangle.t],
    [\\triangleleft],
    [triangle.l.small],
    [\\triangleright],
    [triangle.r.small],
    [\\uparrow],
    [arrow.t],
    [\\updownarrow],
    [arrow.t.b],
    [\\upharpoonright],
    [harpoon.tr],
    [\\uplus],
    [union.plus],
    [\\upsilon],
    [upsilon],
    [\\varepsilon],
    [epsilon],
    [\\varphi],
    [phi],
    [\\varpi],
    [pi.alt],
    [\\varrho],
    [rho.alt],
    [\\varsigma],
    [sigma.alt],
    [\\vartheta],
    [theta.alt],
    [\\vdash],
    [tack.r],
    [\\vdots],
    [dots.v],
    [\\vee],
    [or],
    [\\wedge],
    [and],
    [\\wr],
    [wreath],
    [\\xi],
    [xi],
    [\\zeta],
    [zeta],
"""

# 匹配 [\\latex], [typst] 结构的正则
pattern = r"(\[\\.*?\]),\s*(\[(.*?)\])"

def transform(match):
    latex_item = match.group(1) # [\\iota]
    typst_item = match.group(2) # [iota]
    # 提取第一个函数名用于渲染（处理类似 brace, brace.l 的情况）
    raw_name = match.group(3).split(',')[0].strip() 
    return f"{latex_item}, [${raw_name}$], {typst_item}"

result = re.sub(pattern, transform, source_data)
print(result)

with open("result.txt", "w", encoding="utf-8") as f:
    f.write(result)