
#import "../index.typ": template, tufted
// #import "@preview/mitex:0.2.6": *

#show: template
#import "../utils.typ": blog-info
#blog-info(
  title: "Equivalent Typst Function Names of LaTeX Commands",
  sub-title: "从 LaTeX 命令到 Typst 函数的等价名称",
  date: "2026-01-02",
  author: "Jianrui Lyu(tolvjr@163.com)原著, 周树勋补充",
  show-outline: true,
)


= 从 LaTeX 命令到 Typst 函数的等价转换

Equivalent Typst Function Names of LaTeX Commands

// #let total-pages = 5

// #for i in range(1, total-pages + 1) {
//   image("../assests/Latex2typst.pdf", width: 100%, page: i)
//   pagebreak()
// }

#set heading(numbering: "1.1")

// 辅助函数：创建4列对照表
#let mapping-table(data) = {
  table(
    columns: (2fr, 1.5fr, 2fr, 1.5fr),
    stroke: none,
    inset: 4pt,
    align: horizon,
    fill: (x, y) => {
      if y == 0 {
        gray.lighten(90%) // 表头背景颜色
      } else {
        // 实现斑马线逻辑：行(y)交替，或者保留你原来的列交替
        if calc.even(y) { luma(97%) } else { white }
      }
    },
    table.hline(y: 0, stroke: 1.5pt),
    table.header([*LaTeX Command*], [*Typst Function*], [*LaTeX Command*], [*Typst Function*]),
    table.hline(y: 1, stroke: 0.8pt),
    ..data,
    table.hline(stroke: 1.5pt),
  )
}

#let mapping-table-5(data) = {
  table(
    columns: 6,
    stroke: none,
    inset: 4pt,
    align: horizon,
    fill: (x, y) => {
      if y == 0 {
        gray.lighten(90%) // 表头背景颜色
      } else {
        // 实现斑马线逻辑：行(y)交替，或者保留你原来的列交替
        if calc.even(y) { luma(97%) } else { white }
      }
    },
    table.hline(y: 0, stroke: 1.5pt),
    table.header([*LaTeX Command*], [], [*Typst Function*], [*LaTeX Command*], [], [*Typst Function*]),
    table.hline(y: 1, stroke: 0.8pt),
    ..data,
    table.hline(stroke: 1.5pt),
  )
}

// // --- 封面与标题 ---
// #align(center)[
//   #text(1.5em, weight: "bold")[Equivalent Typst Function Names of LaTeX Commands] \
//   #v(1em)
//   Jianrui Lyu (tolvjr\@163.com) \
//   Version 2024A (2024-02-20)
// ]

#v(2em)

本文档列出了与 LaTeX 命令等效的 Typst 函数名称。仅包含 LaTeX 格式或 amsmath 宏包提供的数学符号。

// --- 正文内容 ---

= Text Environments

#table(
  columns: (2fr, 1.5fr, 2fr, 1.5fr),
  stroke: none,
  inset: 8pt,
  align: horizon,
  fill: (x, y) => {
    if y == 0 {
      gray.lighten(90%) // 表头背景颜色
    } else {
      // 实现斑马线逻辑：行(y)交替，或者保留你原来的列交替
      if calc.even(y) { luma(97%) } else { white }
    }
  },
  table.hline(y: 0, stroke: 1.5pt),
  table.header([*LaTeX Environment*], [*Typst Function*], [*LaTeX Environment*], [*Typst Function*]),
  table.hline(y: 1, stroke: 0.8pt),
  [description], [terms], [enumerate], [enum],
  [figure], [figure], [itemize], [list],
  [minipage], [block], [table], [figure],
  [tabular], [table], [thebibliography], [bibliography],
  [tabularx], [table, grid], [verbatim], [raw],
  table.hline(stroke: 1.5pt),
)

= Text Commands

#mapping-table((
  [\\chapter],
  [heading],
  [\\cite],
  [cite],
  [\\documentclass],
  [import],
  [\\emph],
  [emph],
  [\\fbox],
  [rect],
  [\\href],
  [link],
  [\\hspace],
  [h],
  [\\include],
  [include],
  [\\includegraphics],
  [image],
  [\\label],
  [label],
  [\\lowercase],
  [lower],
  [\\medspace],
  [medium],
  [\\newcommand],
  [let],
  [\\newcounter],
  [let],
  [\\newenvironment],
  [let],
  [\\newlength],
  [let],
  [\\pagebreak],
  [pagebreak],
  [\\parbox],
  [block],
  [\\part],
  [heading],
  [\\qquad],
  [wide],
  [\\quad],
  [quad],
  [\\ref],
  [ref],
  [\\renewcommand],
  [let],
  [\\renewenvironment],
  [let],
  [\\section],
  [heading],
  [\\setcounter],
  [let],
  [\\setlength],
  [let],
  [\\subsection],
  [heading],
  [\\subsubsection],
  [heading],
  [\\textbf],
  [strong],
  [\\textit],
  [text(style: "italic")],
  [\\textmd],
  [text(style: "normal")],
  [\\textrm],
  [text],
  [\\textsc],
  [smallcaps],
  [\\textsf],
  [text],
  [\\textsl],
  [text(style: "oblique")],
  [\\texttt],
  [text],
  [\\thickspace],
  [thick],
  [\\thinspace],
  [thin],
  [\\underline],
  [underline],
  [\\uppercase],
  [upper],
  [\\url],
  [link],
  [\\usepackage],
  [import],
  [\\verb],
  [raw],
  [\\vspace],
  [v],
  [],
  [],
))

= Math Environments

#table(
  columns: (2fr, 1.5fr, 2fr, 1.5fr),
  stroke: none,
  inset: 4pt,
  align: horizon,
  fill: (x, y) => {
    if y == 0 {
      gray.lighten(90%) // 表头背景颜色
    } else {
      // 实现斑马线逻辑：行(y)交替，或者保留你原来的列交替
      if calc.even(y) { luma(97%) } else { white }
    }
  },
  table.hline(y: 0, stroke: 1.5pt),
  table.header([*LaTeX Environment*], [*Typst Function*], [*LaTeX Environment*], [*Typst Function*]),
  table.hline(y: 1, stroke: 0.8pt),
  [Bmatrix], [mat(delim: "{")], [Vmatrix], [mat(delim: ||)],
  [align], [equation],
  // Typst automatically aligns
  [array], [mat], [bmatrix], [mat(delim: \"\[\")],
  [cases], [cases], [displaymath], [equation],
  [equation], [equation], [math], [math],
  [matrix], [mat], [pmatrix], [mat(delim: "(")],
  [vmatrix], [mat(delim: "|")],
  table.hline(stroke: 1.5pt),
)

+ equation命令使用样例：
  ```typst
  #math.equation(
    block: true,
    numbering: "(1)",
    [$1 + 1 = 2$]
  )
  ```
  #math.equation(
    block: true,
    numbering: "(1)",
    [$1 + 1 = 2$],
  )

+ mat命令使用样例

  ```typst
  $ mat(delim: "{", 1, 2; 3, 4) $
  ```
  $ mat(delim: "{", 1, 2; 3, 4) $
+ cases命令使用样例
  ```typst
  $ cases(2x + y = 1, x - y = 5) $
  ```
  $ cases(2x + y = 1, x - y = 5) $


= Math Commands

#mapping-table((
  [\\arccos],
  [arccos],
  [\\arcsin],
  [arcsin],
  [\\arctan],
  [arctan],
  [\\arg],
  [arg],
  [\\bar],
  [macron],
  [\\binom],
  [binom],
  [\\boldsymbol],
  [bold],
  [\\cos],
  [cos],
  [\\cosh],
  [cosh],
  [\\cot],
  [cot],
  [\\coth],
  [coth],
  [\\csc],
  [csc],
  [\\dbinom],
  [binom],
  [\\ddot],
  [diaer, dot.double],
  [\\deg],
  [deg],
  [\\det],
  [det],
  [\\dfrac],
  [frac],
  [\\dim],
  [dim],
  [\\dot],
  [dot],
  [\\exp],
  [exp],
  [\\frac],
  [frac],
  [\\gcd],
  [gcd],
  [\\hat],
  [hat],
  [\\hspace],
  [h],
  [\\inf],
  [inf],
  [\\ker],
  [ker],
  [\\left],
  [lr],
  [\\lg],
  [lg],
  [\\lim],
  [lim],
  [\\liminf],
  [liminf],
  [\\limsup],
  [limsup],
  [\\ln],
  [ln],
  [\\log],
  [log],
  [\\mathbb],
  [bb],
  [\\mathcal],
  [cal],
  [\\max],
  [max],
  [\\min],
  [min],
  [\\mod],
  [mod],
  [\\overbrace],
  [overbrace],
  [\\overline],
  [overline],
  [\\qquad],
  [wide],
  [\\quad],
  [quad],
  [\\right],
  [lr],
  [\\sec],
  [sec],
  [\\sin],
  [sin],
  [\\sinh],
  [sinh],
  [\\sqrt],
  [sqrt, root],
  [\\sup],
  [sup],
  [\\tan],
  [tan],
  [\\tanh],
  [tanh],
  [\\tbinom],
  [binom],
  [\\tfrac],
  [frac],
  [\\tilde],
  [tilde],
  [\\underbrace],
  [underbrace],
  [\\vec],
  [arrow],
  [\\widehat],
  [hat],
))

= Math Symbols

#mapping-table-5(
  (
    [\\Cap],
    [$sect.double$],
    [sect.double],
    [\\Cup],
    [$union.double$],
    [union.double],
    [\\Delta],
    [$Delta$],
    [Delta],
    [\\Gamma],
    [$Gamma$],
    [Gamma],
    [\\Join],
    [$join$],
    [join],
    [\\Lambda],
    [$Lambda$],
    [Lambda],
    [\\Longrightarrow],
    [$arrow.double.r.long$],
    [arrow.double.r.long],
    [\\Omega],
    [$Omega$],
    [Omega],
    [\\Phi],
    [$Phi$],
    [Phi],
    [\\Pi],
    [$Pi$],
    [Pi],
    [\\Psi],
    [$Psi$],
    [Psi],
    [\\Rightarrow],
    [$arrow.double.r$],
    [arrow.double.r],
    [\\Sigma],
    [$Sigma$],
    [Sigma],
    [\\Theta],
    [$Theta$],
    [Theta],
    [\\aleph],
    [$alef$],
    [alef],
    [\\alpha],
    [$alpha$],
    [alpha],
    [\\angle],
    [$angle$],
    [angle],
    [\\approx],
    [$approx$],
    [approx],
    [\\approxeq],
    [$approx.eq$],
    [approx.eq],
    [\\ast],
    [$ast$],
    [ast],
    [\\beta],
    [$beta$],
    [beta],
    [\\bigcap],
    [$sect.big$],
    [sect.big],
    [\\bigcirc],
    [$circle.big$],
    [circle.big],
    [\\bigcup],
    [$union.big$],
    [union.big],
    [\\bigodot],
    [$dot.circle.big$],
    [dot.circle.big],
    [\\bigoplus],
    [$plus.circle.big$],
    [plus.circle.big],
    [\\bigotimes],
    [$times.circle.big$],
    [times.circle.big],
    [\\bigsqcup],
    [$union.sq.big$],
    [union.sq.big],
    [\\bigtriangledown],
    [$triangle.t$],
    [triangle.t],
    [\\bigtriangleup],
    [$triangle.b$],
    [triangle.b],
    [\\biguplus],
    [$union.plus.big$],
    [union.plus.big],
    [\\bigvee],
    [$or.big$],
    [or.big],
    [\\bigwedge],
    [$and.big$],
    [and.big],
    [\\bullet],
    [$bullet$],
    [bullet],
    [\\cap],
    [$sect$],
    [sect],
    [\\cdot],
    [$dot.op$],
    [dot.c, dot.op],
    [\\cdots],
    [$dots.c$],
    [dots.c],
    [\\checkmark],
    [$checkmark$],
    [checkmark],
    [\\chi],
    [$chi$],
    [chi],
    [\\circ],
    [$compose$],
    [circle.small,compose],
    [\\colon],
    [$colon$],
    [colon],
    [\\cong],
    [$tilde.equiv$],
    [tilde.equiv],
    [\\coprod],
    [$product.co$],
    [product.co],
    [\\cup],
    [$union$],
    [union],
    [\\curlyvee],
    [$or.curly$],
    [or.curly],
    [\\curlywedge],
    [$and.curly$],
    [and.curly],
    [\\dagger],
    [$dagger$],
    [dagger],
    [\\dashv],
    [$tack.l$],
    [tack.l],
    [\\ddagger],
    [$dagger.double$],
    [dagger.double],
    [\\delta],
    [$delta$],
    [delta],
    [\\ddots],
    [$dots.down$],
    [dots.down],
    [\\diamond],
    [$diamond$],
    [diamond],
    [\\div],
    [$div$],
    [div],
    [\\divideontimes],
    [$times.div$],
    [times.div],
    [\\dotplus],
    [$plus.dot$],
    [plus.dot],
    [\\downarrow],
    [$arrow.b$],
    [arrow.b],
    [\\ell],
    [$ell$],
    [ell],
    [\\emptyset],
    [$nothing$],
    [nothing],
    [\\epsilon],
    [$epsilon.alt$],
    [epsilon.alt],
    [\\equiv],
    [$equiv$],
    [equiv],
    [\\eta],
    [$eta$],
    [eta],
    [\\exists],
    [$exists$],
    [exists],
    [\\forall],
    [$forall$],
    [forall],
    [\\gamma],
    [$gamma$],
    [gamma],
    [\\ge],
    [$gt.eq$],
    [gt.eq],
    [\\geq],
    [$gt.eq$],
    [gt.eq],
    [\\geqslant],
    [$gt.eq.slant$],
    [gt.eq.slant],
    [\\gg],
    [$gt.double$],
    [gt.double],
    [\\hbar],
    [$planck.reduce$],
    [planck.reduce],
    [\\imath],
    [$dotless.i$],
    [dotless.i],
    [\\iiiint],
    [$integral.quad$],
    [integral.quad],
    [\\iiint],
    [$integral.triple$],
    [integral.triple],
    [\\iint],
    [$integral.double$],
    [integral.double],
    [\\in],
    [$in$],
    [in],
    [\\int],
    [$integral$],
    [integral],
    [\\intercal],
    [$tack.b$],
    [tack.b, top],
    [\\iota],
    [$iota$],
    [iota],
    [\\jmath],
    [$dotless.j$],
    [dotless.j],
    [\\kappa],
    [$kappa$],
    [kappa],
    [\\lambda],
    [$lambda$],
    [lambda],
    [\\langle],
    [$angle.l$],
    [angle.l],
    [\\lbrace],
    [$brace$],
    [brace, brace.l],
    [\\lbrack],
    [$bracket$],
    [bracket, bracket.l],
    [\\ldots],
    [$dots$],
    [dots, dots.l],
    [\\le ],
    [$lt.eq$],
    [lt.eq],
    [\\leadsto],
    [$arrow.squiggly$],
    [arrow.squiggly],
    [\\leftarrow],
    [$arrow.l$],
    [arrow.l],
    [\\leftthreetimes],
    [$times.three.l$],
    [times.three.l],
    [\\leftrightarrow],
    [$arrow.l.r$],
    [arrow.l.r],
    [\\lhd],
    [$triangle.l$],
    [triangle.l],
    [\\ll],
    [$lt.double$],
    [lt.double],
    [\\longmapsto],
    [$arrow.long.bar$],
    [arrow.long.bar],
    [\\longrightarrow],
    [$arrow.r.long$],
    [arrow.r.long],
    [\\ltimes],
    [$times.l$],
    [times.l],
    [\\mapsto],
    [$arrow.bar$],
    [arrow.bar],
    [\\measuredangle],
    [$angle.arc$],
    [angle.arc],
    [\\mid],
    [$divides$],
    [divides],
    [\\models],
    [$models$],
    [models],
    [\\mp],
    [$minus.plus$],
    [minus.plus],
    [\\mu],
    [$mu$],
    [mu],
    [\\nRightarrow],
    [$arrow.double.r.not$],
    [arrow.double.r.not],
    [\\nabla],
    [$nabla$],
    [nabla],
    [\\ncong],
    [$tilde.equiv.not$],
    [tilde.equiv.not],
    [\\ne],
    [$eq.not$],
    [eq.not ],
    [\\neg],
    [$not$],
    [not],
    [\\neq],
    [$eq.not$],
    [eq.not ],
    [\\nmid],
    [$divides.not$],
    [divides.not],
    [\\notin],
    [$in.not$],
    [in.not],
    [\\nleftarrow],
    [$arrow.l.not$],
    [arrow.l.not],
    [\\nrightarrow],
    [$arrow.r.not$],
    [arrow.r.not],
    [\\nsim],
    [$tilde.not$],
    [tilde.not],
    [\\nu],
    [$nu$],
    [nu],
    [\\odot],
    [$dot.circle$],
    [dot.circle],
    [\\oint],
    [$integral.cont$],
    [integral.cont],
    [\\omega],
    [$omega$],
    [omega],
    [\\ominus],
    [$minus.circle$],
    [minus.circle],
    [\\oplus],
    [$plus.circle$],
    [plus.circle],
    [\\otimes],
    [$times.circle$],
    [times.circle],
    [\\parallel],
    [$parallel$],
    [parallel],
    [\\partial],
    [$diff$],
    [diff],
    [\\perp],
    [$perp$],
    [perp],
    [\\phi],
    [$phi.alt$],
    [phi.alt],
    [\\pi],
    [$pi$],
    [pi],
    [\\pm],
    [$plus.minus$],
    [plus.minus],
    [\\prec],
    [$prec$],
    [prec],
    [\\preceq],
    [$prec.eq$],
    [prec.eq],
    [\\prime],
    [$prime$],
    [prime],
    [\\prod],
    [$product$],
    [product],
    [\\propto],
    [$prop$],
    [prop],
    [\\psi],
    [$psi$],
    [psi],
    [\\rangle],
    [$angle.r$],
    [angle.r],
    [\\rbrace],
    [$brace.r$],
    [brace.r],
    [\\rbrack],
    [$bracket.r$],
    [bracket.r],
    [\\rhd],
    [$triangle.r$],
    [triangle.r],
    [\\rho],
    [$rho$],
    [rho],
    [\\rightarrow],
    [$arrow.r$],
    [arrow.r ],
    [\\rightthreetimes],
    [$times.three.r$],
    [times.three.r],
    [\\rtimes],
    [$times.r$],
    [times.r],
    [\\setminus],
    [$without$],
    [without],
    [\\sigma],
    [$sigma$],
    [sigma],
    [\\sim],
    [$tilde$],
    [tilde],
    [\\simeq],
    [$tilde.eq$],
    [tilde.eq],
    [\\sqcap],
    [$sect.sq$],
    [sect.sq],
    [\\sqcup],
    [$union.sq$],
    [union.sq],
    [\\star],
    [$star$],
    [star],
    [\\subset],
    [$subset$],
    [subset],
    [\\subseteq],
    [$subset.eq$],
    [subset.eq],
    [\\subsetneq],
    [$subset.neq$],
    [subset.neq],
    [\\succ],
    [$succ$],
    [succ],
    [\\succeq],
    [$succ.eq$],
    [succ.eq],
    [\\sum],
    [$sum$],
    [sum],
    [\\supset],
    [$supset$],
    [supset],
    [\\supseteq],
    [$supset.eq$],
    [supset.eq],
    [\\supsetneq],
    [$supset.neq$],
    [supset.neq],
    [\\tau],
    [$tau$],
    [tau],
    [\\theta],
    [$theta$],
    [theta],
    [\\times],
    [$times$],
    [times],
    [\\to],
    [$arrow.r$],
    [arrow.r],
    [\\triangle],
    [$triangle.t$],
    [triangle.t],
    [\\triangleleft],
    [$triangle.l.small$],
    [triangle.l.small],
    [\\triangleright],
    [$triangle.r.small$],
    [triangle.r.small],
    [\\uparrow],
    [$arrow.t$],
    [arrow.t],
    [\\updownarrow],
    [$arrow.t.b$],
    [arrow.t.b],
    [\\upharpoonright],
    [$harpoon.tr$],
    [harpoon.tr],
    [\\uplus],
    [$union.plus$],
    [union.plus],
    [\\upsilon],
    [$upsilon$],
    [upsilon],
    [\\varepsilon],
    [$epsilon$],
    [epsilon],
    [\\varphi],
    [$phi$],
    [phi],
    [\\varpi],
    [$pi.alt$],
    [pi.alt],
    [\\varrho],
    [$rho.alt$],
    [rho.alt],
    [\\varsigma],
    [$sigma.alt$],
    [sigma.alt],
    [\\vartheta],
    [$theta.alt$],
    [theta.alt],
    [\\vdash],
    [$tack.r$],
    [tack.r],
    [\\vdots],
    [$dots.v$],
    [dots.v],
    [\\vee],
    [$or$],
    [or],
    [\\wedge],
    [$and$],
    [and],
    [\\wr],
    [$wreath$],
    [wreath],
    [\\xi],
    [$xi$],
    [xi],
    [\\zeta],
    [$zeta$],
    [zeta],
  ),
)



= References

+ Jim Hefferon, LaTeX Math for Undergrads, https://gitlab.com/jim.hefferon/undergradmath, 2020.
+ Johan Xie, Typst Math for Undergrads, https://github.com/johanvx/typst-undergradmath, 2023.
+ Scott Pakin, The Comprehensive LaTeX Symbol List, https://ctan.org/pkg/comprehensive, 2024.
+ Jianrui Lyu,Equivalent Typst Function Names of LaTeX Commands, #link("https://github.com/hblgzsx/Academic-Homepage-Typst-Tufted/blob/41ac30040edbcaed0dcdd19b7b00187e4dfa40af/content/blog/assests/Latex2typst.pdf", "https://github.com/hblgzsx/Academic-Homepage-Typst-Tufted/blob/41ac30040edbcaed0dcdd19b7b00187e4dfa40af/content/blog/assests/Latex2typst.pdf")
